name: glnexus
description: merge gVCF files and perform joint variant calling
keywords:
    - merge
    - gvcf
tools:
    - glnexus:
        description: |
            GLnexus allows gVCF merging and joint variant calling for population sequencing 
            projects in a scalable fashion.
        homepage: https://github.com/dnanexus-rnd/GLnexus
        documentation: https://github.com/dnanexus-rnd/GLnexus/wiki/Getting-Started
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - gvcfs:
        type: file
        description: Input genomic vcf files
output:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: Compressed VCF file
        pattern: "*.vcf.gz"
authors:
    - "@ramprasadn"
