lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/multiqc_config.yaml
    - lib/NfcoreSchema.groovy
    - .github/workflows/linting.yml
